In [1]:
import torch

# Torch Tensors

In [2]:
#This is a 1-D Tensor or a list
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
#This is a 2-D Tensor is same as numpy array.
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
#The size of the tensors, shape and size same result. size is a method, shape is attribute

print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
# float tensor
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [7]:
# double tensor. higher precision
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
#Reshape b . the method is called
#Note: If one of the dimensions is -1, its size can be inferred. find how many rows itself
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-1.2028,  0.9689, -0.3888,  0.3172],
         [-0.1851,  0.9294,  0.6203,  1.7806],
         [ 0.2875, -1.0042,  0.5126, -0.1515]],

        [[ 0.3248, -0.1848,  1.6202,  0.6247],
         [ 0.1803,  0.4576, -0.1618,  0.3078],
         [-0.6284,  1.9864, -0.6840,  1.5325]]])
tensor([[-1.2028,  0.9689, -0.3888,  0.3172, -0.1851,  0.9294,  0.6203,  1.7806,
          0.2875, -1.0042,  0.5126, -0.1515],
        [ 0.3248, -0.1848,  1.6202,  0.6247,  0.1803,  0.4576, -0.1618,  0.3078,
         -0.6284,  1.9864, -0.6840,  1.5325]])
tensor([[-1.2028,  0.9689, -0.3888,  0.3172, -0.1851

In [15]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.6079, 0.9923, 0.6447, 0.8261],
        [0.6858, 0.7344, 0.1313, 0.1958],
        [0.9620, 0.6326, 0.9108, 0.8906],
        [0.6197, 0.5777, 0.0268, 0.1291]])


In [16]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.0479, -1.6766, -0.0319,  1.7984],
        [ 0.9718,  0.0248,  1.3939,  0.6909],
        [-0.0654, -0.6738, -0.1405,  0.8484],
        [ 0.6353,  1.0153,  0.9020, -0.5619]])
torch.float32


In [17]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([6, 7, 8, 7, 7])
torch.int64


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[6, 6, 7],
        [8, 8, 9],
        [6, 6, 6]])


In [19]:
#Get the number of elements in in_array
print(torch.numel(in_array))
#Get the number of elements in in_array
print(torch.numel(in_array2))

5
9


In [20]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor, take the same size
print(r2_like)

tensor([[-0.9377, -0.0390,  0.3038, -0.8039],
        [ 1.1975, -0.1796,  0.2046,  0.1063],
        [-0.3969,  0.8826,  0.8853,  1.1564],
        [-1.1438, -0.1381, -0.3208,  0.8043]], dtype=torch.float64)


In [22]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 0.5600, -0.6843,  0.6128,  2.6245],
        [ 1.6577,  0.7592,  1.5252,  0.8866],
        [ 0.8966, -0.0411,  0.7703,  1.7389],
        [ 1.2550,  1.5930,  0.9287, -0.4328]])


In [23]:
#In-place addition (change the value of r2) . notice the underscore
r2.add_(r)    
print(r2)

tensor([[ 0.5600, -0.6843,  0.6128,  2.6245],
        [ 1.6577,  0.7592,  1.5252,  0.8866],
        [ 0.8966, -0.0411,  0.7703,  1.7389],
        [ 1.2550,  1.5930,  0.9287, -0.4328]])


In [24]:
# matrix sclicing
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item()) # extract the number from tensor
print(r2[2,:])

tensor([-0.6843,  0.7592, -0.0411,  1.5930])
tensor([[ 0.5600, -0.6843],
        [ 1.6577,  0.7592],
        [ 0.8966, -0.0411],
        [ 1.2550,  1.5930]])
tensor([[ 0.5600, -0.6843,  0.6128,  2.6245],
        [ 1.6577,  0.7592,  1.5252,  0.8866],
        [ 0.8966, -0.0411,  0.7703,  1.7389]])
tensor(1.7389)
1.738911747932434
tensor([ 0.8966, -0.0411,  0.7703,  1.7389])


## Numpy Bridge

In [25]:
import numpy as np

In [26]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

tensor([[ 0.5600, -0.6843,  0.6128,  2.6245],
        [ 1.6577,  0.7592,  1.5252,  0.8866],
        [ 0.8966, -0.0411,  0.7703,  1.7389],
        [ 1.2550,  1.5930,  0.9287, -0.4328]], device='cuda:0')


In [29]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[ 0.5600, -0.6843,  0.6128,  2.6245],
        [ 1.6577,  0.7592,  1.5252,  0.8866],
        [ 0.8966, -0.0411,  0.7703,  1.7389],
        [ 1.2550,  1.5930,  0.9287, -0.4328]], device='cuda:0')


In [31]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [32]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [35]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[ 0.8210, -0.8677, -0.6182,  0.6241,  1.2906],
        [ 0.5490,  1.3955, -0.4172, -0.9109,  1.1844]])
tensor([[-1.0315, -1.2055,  0.7563, -0.0667,  0.8972],
        [-1.1097,  0.8922, -1.0103, -0.2262,  1.0418],
        [ 0.3933,  0.9592, -0.6547,  0.9232, -0.0781]])


tensor([[ 0.8210, -0.8677, -0.6182,  0.6241,  1.2906],
        [ 0.5490,  1.3955, -0.4172, -0.9109,  1.1844],
        [-1.0315, -1.2055,  0.7563, -0.0667,  0.8972],
        [-1.1097,  0.8922, -1.0103, -0.2262,  1.0418],
        [ 0.3933,  0.9592, -0.6547,  0.9232, -0.0781]])


tensor([[ 1.1262, -0.4261,  0.7666],
        [-1.5131, -2.9832, -0.4148]])
tensor([[ 0.2421, -0.2253, -0.8906,  1.1100, -0.4303],
        [ 0.1736, -1.4240, -0.7344,  2.2381,  0.2373]])


tensor([[ 1.1262, -0.4261,  0.7666,  0.2421, -0.2253, -0.8906,  1.1100, -0.4303],
        [-1.5131, -2.9832, -0.4148,  0.1736, -1.4240, -0.7344,  2.2381,  0.2373]])




## Adding Dimensions to Tensors

In [36]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0) # 1*4 dimension
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1) # 4 rows 1 column
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.1041, 0.0649, 0.6080, 0.6900],
         [0.5914, 0.1414, 0.7212, 0.7248],
         [0.1020, 0.4382, 0.7092, 0.2439]],

        [[0.6563, 0.4727, 0.6590, 0.3446],
         [0.1204, 0.3937, 0.9957, 0.3056],
         [0.0991, 0.9759, 0.8695, 0.5162]]])


tensor([[0.6080, 0.7212, 0.7092],
        [0.6590, 0.9957, 0.8695]])
torch.Size([2, 3])


tensor([[[0.6080],
         [0.7212],
         [0.7092]],

        [[0.6590],
         [0.9957],
         [0.8695]]])
torch.Size([2, 3, 1])


## AutoGrad or Automatic Differentiation

In [39]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [40]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [41]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [42]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [43]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
